### ISSUE TITLE
Update needed for newest version and lack of compatibility with "older" versions

### ISSUE THREAD

**Issue by CodeAlDente** [codefog/contao-cookiebar#6] opened 2015-10-10 00:57 UTC
Hi there!

First of all, thank you very much for your valuable time working on this. :+1: 

As far I can see from the contao website, this extension doesn't support the newst LTS version of Contao (currently 3.5.4). But it also seems not to support my current installed version 3.5.2. Because I don't get the option to enable this extension, it's just missing between the settings (root site configuration).

Oh and by the way, I'm using the Composer plugin to install and manage extensions.

**Comment by qzminski** [comment] 2015-10-10 07:11
I have updated the compatibility in extension manager. I have just installed the extension on Contao 3.5.4 and it works fine. Please make sure that you have updated the database and rebuilt the internal cache. If it still does not work you can still try to update your installation to 3.5.4 and then it should work.

![2015-10-10 at 09 09](https://cloud.githubusercontent.com/assets/193483/10409823/e6af46c6-6f2e-11e5-8ce2-32d5aefaf817.png)

**Comment by CodeAlDente** [comment] 2015-10-10 13:41
I've updated Contao to the newest version and tried to get this extension working again. But it failed again.

**I also tried to install the extension from the contao legacy package. But it doesn't work either.**

![1444483799](https://cloud.githubusercontent.com/assets/10899559/10411411/db4c5dec-6f64-11e5-8f73-97915f9a2772.png)
![1444483730](https://cloud.githubusercontent.com/assets/10899559/10411412/db6bdba4-6f64-11e5-8f9d-5972f233e82b.png)
![1444483606](https://cloud.githubusercontent.com/assets/10899559/10411413/db6c8586-6f64-11e5-9c21-b6227e61cf21.png)

**Comment by qzminski** [comment] 2015-10-10 19:21
This is really strange. Have you tried to rebuild the internal cache manually (using Maintenance module)? Do you have some php cache enabled perhaps (opcache)?

**Comment by CodeAlDente** [comment] 2015-10-10 19:41
Yes, I also tried to rebuild the internal cache. Even manually, but it didn't help. And Yes, OPcache is installed and enabled. Could you please provide me with your composer settings? I'd like to have a look on it.

Here is mine (yes, I also tried to empty the composer cache).

![1444505800](https://cloud.githubusercontent.com/assets/10899559/10412933/1c4224ee-6f97-11e5-93f1-002ec4ec9ea5.png)

**Comment by qzminski** [comment] 2015-10-12 06:39
I don't think composer settings matter here. Can you check if there is a symlink /system/modules/cookiebar ?

**Comment by CodeAlDente** [comment] 2015-10-12 17:47
Oh okay, I thought I'm using the wrong build.

The symlink doesn't exist. Even if I re-synch the composer packages. I do see the message, that everything has been created successfully, but in fact, there is no symlink - atleast for cookiebar. I only have the following folders:

- /composer/vendor/contao-legacy/cookiebar
- /composer/vendor/contao/core/system/modules/cookiebar

**Comment by qzminski** [comment] 2015-10-12 17:51
I think the problem is with the composer because your contao/core package is marked as project so this is definitely wrong. Also for some reason it does not create symlinks which is the direct cause of your problem. This is not an extension issue so I have to mark it as invalid. Please also have a look at this issue:

https://github.com/contao-community-alliance/composer-plugin/issues/44

Have you tried to removed contao-legacy/cookiebar package and then install codefog/contao-cookiebar?

**Closed** 2015-10-12 17:51 UTC
Labels: invalid

**Comment by CodeAlDente** [comment] 2015-10-12 17:58
> Also for some reason it does not create symlinks which is the direct cause of your problem.

I see. But how can I fix this? There is no solution in the mentioned ticket, that could help here.

> Have you tried to removed contao-legacy/cookiebar package and then install codefog/contao-cookiebar?

Of course, as I said before.

![1444672386](https://cloud.githubusercontent.com/assets/10899559/10434728/9fb364ac-711b-11e5-9bc1-e24c41d01ed5.png)

**Comment by qzminski** [comment] 2015-10-12 18:13
Oh sorry, didn't notice that. I had similar issue on the Windows Server and the only solution I came up with was creating a temporary custom PHP file that created symlink with the below function.

https://secure.php.net/manual/en/function.symlink.php

**Comment by CodeAlDente** [comment] 2015-10-12 19:00
Okay, the idea to setup the symlink manually sounds good. Since I'm able to work on a shell, it's very handy, too.

And I finally see the option to enable cookiebar. But when I do so, I immediately get the following error message:

> Fatal error: Uncaught exception Exception with message Query error: **Unknown column 'cookiebar_enable' in 'field list'** (UPDATE tl_page SET cookiebar_enable='1' WHERE id='1') thrown in system/modules/core/library/Contao/Database/Statement.php on line 295

Seems like the database wasn't even prepared to use cookiebar. (see end of the comment)

```
#0 system/modules/core/library/Contao/Database/Statement.php(264): Contao\Database\Statement->query()
#1 system/modules/core/classes/Ajax.php(380): Contao\Database\Statement->execute('1')
#2 system/modules/core/classes/Backend.php(414): Contao\Ajax->executePostActions(Object(Contao\DC_Table))
#3 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('page')
#4 contao/main.php(20): Contao\BackendMain->run()
#5 {main}
```

:exclamation: **I could fix that by updating the database from the composer menu.** I'd like to keep it for later investigation, because it shows that the installation totally failed. :exclamation:

**Comment by qzminski** [comment] 2015-10-12 19:02
You always need to update the database after extension upload. It can be done via composer, Extension Repository or via Install Tool.

**Comment by CodeAlDente** [comment] 2015-10-12 19:08
Okay. In the past, I noticed that composer updated the database automatically during the installation process. That's why I thought that something went wrong here.
